### ISSUE TITLE
Reactivate Lombok when JDK10 issues gets fixed

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/officeconverter#1]
due to issues in lombok with JDK10 we get compile issues. Lombok has been removed for now, readd it when this are fixed

https://github.com/rzwitserloot/lombok/issues/1723

**Comment by micheljung** [comment]
Lombok* ;-)

**Comment by EugenMayer** [comment]
hehe!

**Comment by EugenMayer** [comment]
done
