### ISSUE TITLE
 Error creating bean with name 'localOfficeManager' defined in class path resource

### ISSUE THREAD

**Issue by dupinderdhiman** [EugenMayer/officeconverter#16]
I am building this application on the windows machine and installed the LibreOffice locally from https://www.libreoffice.org/download/download/ link.

![image](https://user-images.githubusercontent.com/57942222/93089064-62c95b00-f6b8-11ea-9f9d-d3373a610058.png)

Build Successful, but when I am running `jar` this error is coming

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'converterService' defined in URL [jar:file:/E:/repos/Github/officeconverter/tmp/gradle-officeconverter/build/libs/officeconverter-unspecified.jar!/BOOT-INF/classes!/de/kontextwork/converter/service/ConverterService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localOfficeManager' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLocalAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jodconverter.core.office.OfficeManager]: Factory method 'localOfficeManager' threw exception; nested exception is java.lang.NullPointerException`

**Comment by EugenMayer** [comment]
Sorry, not offering any developer support here. Please seek https://github.com/sbraconnier/jodconverter for further advice
