### ISSUE TITLE
Which License

### ISSUE THREAD

**Issue by doricci** [EugenMayer/officeconverter#5]
Hello,

I just saw your project but I can find any license on it, could you please share the license that you will/want to put on this project?

best regards

**Comment by pgassmann** [comment]
Hi @EugenMayer The License is still undefined, two years after this notice was placed:
`Yet unclear, do not yet include this in commercial products until further defined. TBA`

Do you consider putting it under the same Apache 2.0 license as the jodconverter?
https://github.com/sbraconnier/jodconverter/blob/master/LICENSE

What are your current plans with the project?
It's not directly clear to me what the added value/work is in addition to a ready-to-use wrapper of jod-converter?

We would appreciate a clear license to use the tool in a non-profit organisation.

**Comment by EugenMayer** [comment]
> Hi @EugenMayer The License is still undefined, two years after this notice was placed:
> `Yet unclear, do not yet include this in commercial products until further defined. TBA`

This still holds, do not use it in a commercial context.

> 
> Do you consider putting it under the same Apache 2.0 license as the jodconverter?
> https://github.com/sbraconnier/jodconverter/blob/master/LICENSE
Right now, apparently i do not. If at all, it will be a GPL v3 license.

> What are your current plans with the project?
> It's not directly clear to me what the added value/work is in addition to a ready-to-use wrapper of jod-converter?
There are no plans yet, there is no roadmap beside "keep it stable and working with jodconverter". It is ready to use, that's the value. 
 
> We would appreciate a clear license to use the tool in a non-profit organisation.

In a non commercial context you can use the tool in the sense, what jodconverter allows you too ( which is a lot ).
So if the people which are using the project are using it free of charge, in a non profit way, there will be no restrictions at all.

For commercial redistribution and things like that, i would right now rather go the way that you shall not use this project.

I hope this answers the questions you have been looking for :)
