### ISSUE TITLE
Is it possible to override the ```document-formats.json``` file when starting a container of the ```kontextwork-converter``` image?

### ISSUE THREAD

**Issue by cuipengfei** [EugenMayer/officeconverter#75]
Is it possible to override the **document-formats.json** file either as a **docker run parameter or as a k8s env var** when starting a container of the ```kontextwork-converter``` image?

I **guess** the document-formats.json file is not under spring's scope, rather it is a jodconverter specific config file. 

In that case, could it be replaced when starting the container?

**Comment by EugenMayer** [comment]
As you know where the file is located, build your own chart and replace the file using a config-map or mount as you like. It will not be part of this docker image to provide such a flexibility "with" the bootstrap.

**Comment by cuipengfei** [comment]
> As you know where the file is located, build your own chart and replace the file using a config-map or mount as you like. It will not be part of this docker image to provide such a flexibility "with" the bootstrap.

Do you mean using this docker image as-is in the helm chart?
Or does it have to be a modified version of this docker image?

**Comment by EugenMayer** [comment]
you can use either of these options, both would work
